name = "auth-demo-backend"
compatibility_date = "2024-09-24"
compatibility_flags = [ "nodejs_compat" ]

# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "auth-demo"
database_id = "15441b48-dada-4d51-bcfa-595d358e0366"
migrations_dir="drizzle/migrations"

# [ai]
# binding = "AI"